export type TituloInicial = {
  tipo: "pelicula" | "serie";
  nombre: string;
  anio?: number;
  saga?: string;
  orden?: number;
  busquedaTmdb?: string;
};

/** Los 38 títulos aprobados en el ticket 005, en orden de estreno por saga. */
export const CATALOGO_INICIAL: readonly TituloInicial[] = [
  { tipo: "pelicula", nombre: "Pobres Criaturas", anio: 2023, busquedaTmdb: "Poor Things" },
  { tipo: "pelicula", nombre: "Sheep Detectives" },
  {
    tipo: "pelicula",
    nombre: "Eternal Sunshine of the Spotless Mind",
    anio: 2004,
    busquedaTmdb: "Eternal Sunshine of the Spotless Mind",
  },
  { tipo: "pelicula", nombre: "A Monster Calls", anio: 2016, busquedaTmdb: "A Monster Calls" },
  { tipo: "pelicula", nombre: "Forrest Gump", anio: 1994, busquedaTmdb: "Forrest Gump" },
  { tipo: "pelicula", nombre: "Soul", anio: 2020, busquedaTmdb: "Soul" },
  { tipo: "pelicula", nombre: "The Big Short", anio: 2015, busquedaTmdb: "The Big Short" },

  { tipo: "serie", nombre: "Severance", anio: 2022, busquedaTmdb: "Severance" },
  { tipo: "serie", nombre: "Widow's Bay", anio: 2026, busquedaTmdb: "Widow's Bay" },
  { tipo: "serie", nombre: "Andor", anio: 2022, busquedaTmdb: "Andor" },

  {
    tipo: "pelicula",
    nombre: "Star Wars: Episodio IV - Una nueva esperanza",
    anio: 1977,
    saga: "Star Wars",
    orden: 1,
    busquedaTmdb: "Star Wars",
  },
  {
    tipo: "pelicula",
    nombre: "Star Wars: Episodio V - El imperio contraataca",
    anio: 1980,
    saga: "Star Wars",
    orden: 2,
    busquedaTmdb: "The Empire Strikes Back",
  },
  {
    tipo: "pelicula",
    nombre: "Star Wars: Episodio VI - El retorno del Jedi",
    anio: 1983,
    saga: "Star Wars",
    orden: 3,
    busquedaTmdb: "Return of the Jedi",
  },
  {
    tipo: "pelicula",
    nombre: "Star Wars: Episodio I - La amenaza fantasma",
    anio: 1999,
    saga: "Star Wars",
    orden: 4,
    busquedaTmdb: "The Phantom Menace",
  },
  {
    tipo: "pelicula",
    nombre: "Star Wars: Episodio II - El ataque de los clones",
    anio: 2002,
    saga: "Star Wars",
    orden: 5,
    busquedaTmdb: "Attack of the Clones",
  },
  {
    tipo: "pelicula",
    nombre: "Star Wars: Episodio III - La venganza de los Sith",
    anio: 2005,
    saga: "Star Wars",
    orden: 6,
    busquedaTmdb: "Revenge of the Sith",
  },
  {
    tipo: "pelicula",
    nombre: "Star Wars: El despertar de la fuerza",
    anio: 2015,
    saga: "Star Wars",
    orden: 7,
    busquedaTmdb: "The Force Awakens",
  },
  {
    tipo: "pelicula",
    nombre: "Rogue One: Una historia de Star Wars",
    anio: 2016,
    saga: "Star Wars",
    orden: 8,
    busquedaTmdb: "Rogue One: A Star Wars Story",
  },
  {
    tipo: "pelicula",
    nombre: "Star Wars: Los últimos Jedi",
    anio: 2017,
    saga: "Star Wars",
    orden: 9,
    busquedaTmdb: "The Last Jedi",
  },
  {
    tipo: "pelicula",
    nombre: "Han Solo: Una historia de Star Wars",
    anio: 2018,
    saga: "Star Wars",
    orden: 10,
    busquedaTmdb: "Solo: A Star Wars Story",
  },
  {
    tipo: "pelicula",
    nombre: "Star Wars: El ascenso de Skywalker",
    anio: 2019,
    saga: "Star Wars",
    orden: 11,
    busquedaTmdb: "The Rise of Skywalker",
  },
  {
    tipo: "pelicula",
    nombre: "El Mandaloriano y Grogu",
    anio: 2026,
    saga: "Star Wars",
    orden: 12,
    busquedaTmdb: "The Mandalorian and Grogu",
  },

  {
    tipo: "pelicula",
    nombre: "El señor de los anillos: La comunidad del anillo",
    anio: 2001,
    saga: "Tierra Media",
    orden: 1,
    busquedaTmdb: "The Fellowship of the Ring",
  },
  {
    tipo: "pelicula",
    nombre: "El señor de los anillos: Las dos torres",
    anio: 2002,
    saga: "Tierra Media",
    orden: 2,
    busquedaTmdb: "The Two Towers",
  },
  {
    tipo: "pelicula",
    nombre: "El señor de los anillos: El retorno del rey",
    anio: 2003,
    saga: "Tierra Media",
    orden: 3,
    busquedaTmdb: "The Return of the King",
  },
  {
    tipo: "pelicula",
    nombre: "El Hobbit: Un viaje inesperado",
    anio: 2012,
    saga: "Tierra Media",
    orden: 4,
    busquedaTmdb: "The Hobbit: An Unexpected Journey",
  },
  {
    tipo: "pelicula",
    nombre: "El Hobbit: La desolación de Smaug",
    anio: 2013,
    saga: "Tierra Media",
    orden: 5,
    busquedaTmdb: "The Hobbit: The Desolation of Smaug",
  },
  {
    tipo: "pelicula",
    nombre: "El Hobbit: La batalla de los cinco ejércitos",
    anio: 2014,
    saga: "Tierra Media",
    orden: 6,
    busquedaTmdb: "The Hobbit: The Battle of the Five Armies",
  },

  {
    tipo: "pelicula",
    nombre: "Cómo entrenar a tu dragón",
    anio: 2010,
    saga: "Dragones",
    orden: 1,
    busquedaTmdb: "How to Train Your Dragon",
  },
  {
    tipo: "pelicula",
    nombre: "Cómo entrenar a tu dragón 2",
    anio: 2014,
    saga: "Dragones",
    orden: 2,
    busquedaTmdb: "How to Train Your Dragon 2",
  },
  {
    tipo: "pelicula",
    nombre: "Cómo entrenar a tu dragón 3: El mundo oculto",
    anio: 2019,
    saga: "Dragones",
    orden: 3,
    busquedaTmdb: "How to Train Your Dragon: The Hidden World",
  },
  {
    tipo: "pelicula",
    nombre: "Cómo entrenar a tu dragón",
    anio: 2025,
    saga: "Dragones",
    orden: 4,
    busquedaTmdb: "How to Train Your Dragon",
  },

  {
    tipo: "pelicula",
    nombre: "The Amazing Spider-Man",
    anio: 2012,
    saga: "Spider-Man (Garfield)",
    orden: 1,
    busquedaTmdb: "The Amazing Spider-Man",
  },
  {
    tipo: "pelicula",
    nombre: "El poder de Electro",
    anio: 2014,
    saga: "Spider-Man (Garfield)",
    orden: 2,
    busquedaTmdb: "The Amazing Spider-Man 2",
  },

  { tipo: "pelicula", nombre: "Dune", anio: 2021, saga: "Dune", orden: 1, busquedaTmdb: "Dune" },
  {
    tipo: "pelicula",
    nombre: "Dune: Parte Dos",
    anio: 2024,
    saga: "Dune",
    orden: 2,
    busquedaTmdb: "Dune: Part Two",
  },

  {
    tipo: "pelicula",
    nombre: "Spider-Man: Un nuevo universo",
    anio: 2018,
    saga: "Spider-Verse",
    orden: 1,
    busquedaTmdb: "Spider-Man: Into the Spider-Verse",
  },
  {
    tipo: "pelicula",
    nombre: "Spider-Man: A través del Spider-Verso",
    anio: 2023,
    saga: "Spider-Verse",
    orden: 2,
    busquedaTmdb: "Spider-Man: Across the Spider-Verse",
  },
];
